### PR TITLE
improvement: prettify json payloads

### PR DESCRIPTION
**Pull request by imhugofonseca**
Hello! been using asynq and needed the json payloads to look prettier for debugging on the ui so here is the pr. :)

- Added `isJsonPayload` util
- Added `pretiffyPayload` util

### CODE REVIEW

**Review by hibiken — COMMENTED** [review]
Thank you for working on this.

Could you open a separate PR for logo update? I want this PR to just focus on pretty printing of JSON payload. 

When I locally built and ran the app, the log seems to be broken and styles are slightly off for other parts of the app. Would you mind running `make build` and QA testing it locally?

**Comment by imhugofonseca** [comment]
Yeah that makes sense! Since I was just starting to understand the project structure I tried to change a few more things just to understand it better. 

I will clean it up better :)

**Comment by imhugofonseca** [comment]
@hibiken Hey! I've cleaned up this PR could you review it? I've also added the prettier to the `result` fields as well, later we can prettify other payloads, but I think JSON is probably the most common

**Comment by hibiken** [comment]
LGTM! Thank you for this improvement :)

**Pull request merged**
